import image from '../../assets/N-VION/01.bmp'
import image2 from '../../assets/EDGE/R1.bmp'

const realEstateListings = [
    {
      id: 1,
      name: "3 Bedroom Terrace Duplex",
      address: "Orchid Roundabout, Lekki, Lagos",
      price: "NGN 70,000,000",
      description: "A modern 3-bedroom terrace duplex with a big compound and a drainage system.",
      tag: "For Sale",
      imageUrl: image,
    },
    {
      id: 2,
      name: "4 Bedroom Semi-Detached Duplex with BQ",
      address: "VGC, Lekki, Lagos",
      price: "NGN 100,000,000",
      description: "Semi-detached duplex with a boys' quarter and security.",
      tag: "For Sale",
      imageUrl: image2,
    },
    {
      id: 3,
      name: "3 Bedroom Terrace Duplex",
      address: "Ajah, Lagos",
      price: "NGN 80,000,000",
      description: "3-bedroom terrace duplex with a boys' quarter and swimming pool.",
      tag: "For Sale",
      imageUrl: image,
    },
    {
      id: 4,
      name: "4 Bedroom Semi Detached Duplex",
      address: "VGC, Lekki, Lagos",
      price: "NGN 125,000,000",
      description: "A newly built 4-bedroom semi-detached duplex with security.",
      tag: "For Sale",
      imageUrl: image2,
    },
    {
      id: 5,
      name: "Lands for Sale in Lakowe",
      address: "Abijo, Oribanwa, Lakowe, Ajah, Lagos",
      price: "NGN 30,000,000",
      description: "Land for sale with water treatment, nearby restaurants, and 24-hour security.",
      tag: "For Sale",
      imageUrl: "https://example.com/images/land-lakowe.jpg",
    },
    {
      id: 6,
      name: "2 Bedroom Terrace Duplex with BQ",
      address: "Greenwood Park Estate, Abijo, Ajah, Lagos",
      price: "NGN 55,000,000",
      description: "A cozy 2-bedroom terrace duplex with a boys' quarter, security doors, and CCTV cameras.",
      tag: "For Sale",
      imageUrl: "https://example.com/images/2-bedroom-terrace-abijo.jpg",
    },
    {
      id: 7,
      name: "Distress Sale 6 Units of 3 Bedroom Flats",
      address: "Close to Farmers Market, Maitama, Abuja",
      price: "NGN 1,000,000,000",
      description: "6 units of 3-bedroom flats available for a distress sale in a prime location.",
      tag: "For Sale",
      imageUrl: "https://example.com/images/6-units-flats-maitama.jpg",
    },
    {
      id: 8,
      name: "1 Bedroom Apartment",
      address: "Bailey Abule, Ijesha, Yaba, Lagos",
      price: "NGN 70,000/day",
      description: "A 1-bedroom flat apartment for shortlet in a secure location.",
      tag: "Shortlet",
      imageUrl: "https://example.com/images/1-bedroom-apartment-yaba.jpg",
    },
    {
      id: 9,
      name: "Mini Flat",
      address: "Onipanu, Shomolu, Lagos",
      price: "NGN 750,000/year",
      description: "A mini flat apartment available for rent in a central location.",
      tag: "For Rent",
      imageUrl: "https://example.com/images/mini-flat-onipanu.jpg",
    },
    {
      id: 10,
      name: "3 Bedroom Bungalow",
      address: "Ibeju Lekki, Ajah, Lagos",
      price: "NGN 60,000,000",
      description: "A modern 3-bedroom bungalow with ample space and a contemporary design.",
      tag: "For Sale",
      imageUrl: "https://example.com/images/3-bedroom-bungalow-ibeju.jpg",
    },
    {
      id: 11,
      name: "Newly Built 2 Bedroom Apartment",
      address: "Pedro, Shomolu, Lagos",
      price: "NGN 3,000,000/year",
      description: "A newly built 2-bedroom apartment with modern amenities.",
      tag: "For Rent",
      imageUrl: "https://example.com/images/2-bedroom-apartment-pedro.jpg",
    },
    {
      id: 12,
      name: "Newly Built Studio Apartment",
      address: "Oguntolu, Palmgroove, Shomolu, Lagos",
      price: "NGN 700,000/year",
      description: "A compact and affordable studio apartment in a strategic location.",
      tag: "For Rent",
      imageUrl: "https://example.com/images/studio-apartment-oguntolu.jpg",
    },
    {
      id: 13,
      name: "Newly Built Mini Flat",
      address: "Palmgroove, Shomolu, Lagos",
      price: "NGN 600,000/year",
      description: "A new mini flat ideal for singles or small families.",
      tag: "For Rent",
      imageUrl: "https://example.com/images/mini-flat-palmgroove.jpg",
    },
    {
      id: 14,
      name: "Luxury 5 Bedroom Mansion",
      address: "Banana Island, Ikoyi, Lagos",
      price: "NGN 1,200,000,000",
      description: "A luxurious 5-bedroom mansion in a high-end neighborhood.",
      tag: "For Sale",
      imageUrl: "https://example.com/images/5-bedroom-mansion-banana-island.jpg",
    },
    {
      id: 15,
      name: "3 Bedroom Apartment",
      address: "Asokoro, Abuja",
      price: "NGN 45,000,000",
      description: "A spacious 3-bedroom apartment in a secure estate.",
      tag: "For Sale",
      imageUrl: "https://example.com/images/3-bedroom-apartment-asokoro.jpg",
    }
    // Continue adding more properties as needed...
  ];
  
  export default realEstateListings;
  